---
title: "intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(knitr)
opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r setup}
library(VisualizeSimon2Stage)
```


```{r}
(x = clinfun::ph2simon(pu = .2, pa = .4, ep1 = .05, ep2 = .1)) 
```

```{r}
ph2simon4(x) # default type = 'minimax'
```

```{r}
ph2simon4(x, type = 'opt')
```

an alternative print
```{r}
print_ph2simon(x)
```


```{r}
set.seed(1532); r = r_simon(R = 1e2L, prob = .2, object = x)
set.seed(1532); r1 = r_simon.ph2simon4(R = 1e2L, prob = .2, r1 = 5L, n1 = 24L, r = 13L, n = 45L)
stopifnot(identical(r, r1))
```

```{r}
table(attr(r, 'dx')) # look at beta, <10%
set.seed(24315); r2 = r_simon(R = 1e2L, prob = .4, object = x)
table(attr(r2, 'dx')) # look at alpha, <5%
```

```{r}
summary(x)
summary(x, type = c('minimax', 'optimal', 'n1', 'maximax'))
```


```{r}
simon_pr(prob = c(.2, .3, .4), object = x)
simon_pr.ph2simon4(prob = c(.2, .3, .4), r1 = 5L, n1 = 24L, r = 13L, n = 45L) # internal use
```

language for a report
```{r}
Sprintf.ph2simon(x, type = 'minimax')
```

```{r}
Sprintf.ph2simon(x, type = 'optimal')
```

```{r}
Sprintf.ph2simon(x, type = 'n1')
```

```{r}
Sprintf.ph2simon(x, type = 'maximax')
```

```{r}
autoplot(x, type = 'minimax')
```

```{r}
autoplot(x, type = 'optimal')
```

```{r}
autoplot(x, type = 'n1')
```

```{r}
autoplot(x, type = 'maximax')
```

operating characteristics
```{r}
simon_oc(prob = c(A = .3, B = .2, C = .15), object = x, type = 'minimax')
```

```{r}
simon_oc(prob = c(A = .3, B = .2, C = .15), object = x, type = 'optimal')
```

example with r1 = 0
```{r}
(x1 = clinfun::ph2simon(pu = .05, pa = .3, ep1 = .05, ep2 = .2))
# works with all of our functions
autoplot(x1, type = 'optimal') # etc.
```


